server:
  port: 7778

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myblog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: fqh
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    # 文件上传
    multipart:
      # 单个上传文件的最大允许大小
      max-file-size: 1MB
      # HTTP请求中包含的所有文件的总大小的最大允许值
      max-request-size: 1MB
  redis:
    port: 6379
    host: 192.168.150.101
    password: xiaoqian666
mybatis-plus:
  global-config:
    db-config:
      # 逻辑删除的字段
      logic-delete-field: delFlag
      # 代表已删除的值
      logic-delete-value: 1
      # 代表未删除的值
      logic-not-delete-value: 0
      # 主键自增策略，以mysql数据库为准
      id-type: assign_id

logging:
  level:
    com.xiaoqian: debug

oss:
  accessKey: zO8n5Aa6nmCI-TZ8MxLKPF7kpiCrhqhGKH_1kNhQ
  secretKey: F__W48PpRyXDO3S3vNqGWc7Lnh-5lrJ3nqJQm3Og
  bucket: xiaoqian-blog
  external-domain-name: s8of2j3qd.hn-bkt.clouddn.com
